export function generateHtmlDocs(groups, requests) {
    let docsHtml = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>API Documentation - Generated by API Reverse Engineer</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/themes/prism-tomorrow.min.css" rel="stylesheet" />
    <style>
        :root {
            --bg-main: #0a0c10;
            --bg-card: #161b22;
            --border: #30363d;
            --text-main: #c9d1d9;
            --text-muted: #8b949e;
            --accent: #58a6ff;
            --success: #3fb950;
            --warning: #d29922;
            --danger: #f85149;
        }
        body { 
            background-color: var(--bg-main); 
            color: var(--text-main); 
            font-family: 'Plus Jakarta Sans', sans-serif; 
        }
        .mono { font-family: 'JetBrains Mono', monospace; }
        .method-badge { padding: 4px 10px; border-radius: 6px; font-weight: 800; font-size: 0.7rem; color: #fff; text-transform: uppercase; }
        .GET { background-color: #2f81f7; }
        .POST { background-color: #238636; }
        .PUT { background-color: #9e6a03; }
        .PATCH { background-color: #9e6a03; }
        .DELETE { background-color: #da3633; }
        
        aside::-webkit-scrollbar { width: 4px; }
        aside::-webkit-scrollbar-track { background: transparent; }
        aside::-webkit-scrollbar-thumb { background: #30363d; border-radius: 10px; }
        
        pre { border-radius: 12px !important; margin: 0 !important; background: #0d1117 !important; border: 1px solid var(--border) !important; }
        code { font-family: 'JetBrains Mono', monospace !important; font-size: 0.85rem !important; }
        
        .nav-link { 
            display: flex; align-items: center; gap: 8px; padding: 10px 12px; border-radius: 8px;
            color: var(--text-muted); transition: all 0.2s; font-size: 0.9rem; margin-bottom: 2px;
        }
        .nav-link:hover { background: #21262d; color: var(--text-main); }
        .nav-link.active { background: #1f6feb22; color: var(--accent); border-left: 2px solid var(--accent); }

        .endpoint-section { margin-bottom: 5rem; border-top: 1px solid var(--border); padding-top: 3rem; }
        .glass-card { background: var(--bg-card); border: 1px solid var(--border); border-radius: 16px; overflow: hidden; }
        
        .snippet-tab { padding: 8px 16px; font-size: 0.8rem; font-weight: 600; cursor: pointer; border-bottom: 2px solid transparent; color: var(--text-muted); }
        .snippet-tab.active { border-color: var(--accent); color: var(--accent); background: #1f6feb11; }
    </style>
</head>
<body class="antialiased">
    <div class="flex min-h-screen">
        <!-- Sidebar Navigation -->
        <aside class="w-72 h-screen sticky top-0 bg-[#0d1117] border-r border-[#30363d] p-6 overflow-y-auto">
            <div class="mb-10">
                <h1 class="text-xl font-extrabold text-white flex items-center gap-2">
                    <span class="text-blue-500">🕵️‍♂️</span> API Explorer
                </h1>
                <p class="text-[10px] text-slate-500 font-bold uppercase tracking-widest mt-1">Generated Documentation</p>
            </div>
            
            <nav>
                <p class="text-[11px] font-bold text-slate-500 uppercase tracking-widest mb-4">Endpoints</p>
                <div id="sidebar-nav">
`;

    // Map requests to a unified structure
    const unifiedMap = new Map();
    requests.forEach(req => {
        try {
            const urlObj = new URL(req.url);
            let path = urlObj.pathname;
            const parts = path.split('/');
            const normParts = parts.map(p => (!isNaN(p) || p.length > 20) ? ':id' : p);
            path = normParts.join('/');

            const key = `${req.method} ${path}`;
            if (!unifiedMap.has(key)) unifiedMap.set(key, []);
            unifiedMap.get(key).push(req);
        } catch (e) { }
    });

    unifiedMap.forEach((reqs, key) => {
        const method = key.split(' ')[0];
        const path = key.split(' ')[1] || key;
        const id = key.replace(/[^a-z0-9]/gi, '-').toLowerCase();
        docsHtml += `<a href="#${id}" class="nav-link"><span class="method-badge ${method} text-[10px] px-1.5 py-0.5">${method}</span> <span class="truncate">${path}</span></a>`;
    });

    docsHtml += `
                </div>
            </nav>
        </aside>

        <!-- Main Content -->
        <main class="flex-1 p-12 max-w-5xl">
            <header class="mb-20">
                <h2 class="text-5xl font-black text-white mb-4">API Documentation</h2>
                <p class="text-xl text-slate-400">Captured architectural blueprint of the application interface.</p>
                
                <div class="mt-8 flex gap-4">
                    <div class="bg-blue-500/10 border border-blue-500/20 rounded-xl px-4 py-3 flex items-center gap-3">
                        <span class="text-blue-400 font-bold text-xl">${unifiedMap.size}</span>
                        <span class="text-xs text-slate-400 uppercase font-bold">Endpoints Discovered</span>
                    </div>
                </div>
            </header>
`;

    unifiedMap.forEach((reqs, key) => {
        const method = key.split(' ')[0];
        const path = key.split(' ')[1] || key;
        const id = key.replace(/[^a-z0-9]/gi, '-').toLowerCase();
        const latest = reqs[reqs.length - 1];

        let reqBodyStr = latest.requestBody ? JSON.stringify(JSON.parse(latest.requestBody), null, 2) : '// No request body';
        let resBodyStr = latest.responseBody ? JSON.stringify(latest.responseBody, null, 2) : '// No response data';

        // Code Snippet Helpers
        const curl = `curl -X ${method} "${latest.url}" \\ \n  -H "Content-Type: application/json"`;
        const axiosSnippet = `import axios from 'axios';\n\nawait axios.${method.toLowerCase()}("${latest.url}", ${latest.requestBody || '{}'});`;

        docsHtml += `
            <section id="${id}" class="endpoint-section">
                <div class="flex items-center gap-4 mb-8">
                    <span class="method-badge ${method} py-1 px-3 text-sm">${method}</span>
                    <h3 class="text-2xl font-bold text-white mono">${path}</h3>
                </div>

                <div class="grid grid-cols-1 gap-10">
                    <!-- Req / Res -->
                    <div class="glass-card">
                        <div class="flex border-b border-[#30363d]">
                            <div class="snippet-tab active">Response Schema</div>
                            <div class="snippet-tab ml-auto border-none pointer-events-none text-slate-500">Captured Status: ${latest.status}</div>
                        </div>
                        <div class="p-0">
                            <pre><code class="language-json">${escapeHtml(resBodyStr)}</code></pre>
                        </div>
                    </div>

                    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
                        <div class="glass-card">
                            <div class="px-5 py-3 border-b border-[#30363d] text-xs font-bold uppercase text-slate-400 tracking-widest">Request Payload</div>
                            <pre><code class="language-json">${escapeHtml(reqBodyStr)}</code></pre>
                        </div>
                        
                        <div class="glass-card">
                             <div class="px-5 py-3 border-b border-[#30363d] text-xs font-bold uppercase text-slate-400 tracking-widest">Implementation Snippet (Axios)</div>
                             <pre><code class="language-javascript">${escapeHtml(axiosSnippet)}</code></pre>
                        </div>
                    </div>
                    
                    <div class="glass-card">
                        <div class="px-5 py-3 border-b border-[#30363d] text-xs font-bold uppercase text-slate-400 tracking-widest">Raw cURL</div>
                        <pre><code class="language-bash">${escapeHtml(curl)}</code></pre>
                    </div>
                </div>
            </section>
        `;
    });

    if (unifiedMap.size === 0) {
        docsHtml += `<p class="text-slate-400">No API traffic captured yet. Keep the extension open while browsing an app.</p>`;
    }

    docsHtml += `
        </main>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/prism.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-json.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-bash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-javascript.min.js"></script>
    <script>
        // Simple scrollspy / active nav logic
        window.addEventListener('scroll', () => {
            const sections = document.querySelectorAll('.endpoint-section');
            const navLinks = document.querySelectorAll('.nav-link');
            let current = "";
            
            sections.forEach(section => {
                const sectionTop = section.offsetTop;
                if (pageYOffset >= sectionTop - 150) {
                    current = section.getAttribute('id');
                }
            });

            navLinks.forEach(link => {
                link.classList.remove('active');
                if (link.getAttribute('href').includes(current)) {
                    link.classList.add('active');
                }
            });
        });
    </script>
</body>
</html>`;

    return docsHtml;
}

function escapeHtml(unsafe) {
    return String(unsafe)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");
}
