export function generateHtmlDocs(groups, requests) {
    let docsHtml = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Auto-Generated API Documentation</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/themes/prism-tomorrow.min.css" rel="stylesheet" />
    <style>
        body { background-color: #0f172a; color: #f8fafc; font-family: 'Inter', sans-serif; }
        .method-badge { padding: 4px 8px; border-radius: 4px; font-weight: 700; font-size: 0.75rem; color: #fff; }
        .GET { background-color: #3b82f6; } /* blue */
        .POST { background-color: #22c55e; } /* green */
        .PUT { background-color: #f59e0b; } /* amber */
        .PATCH { background-color: #eab308; } /* yellow */
        .DELETE { background-color: #ef4444; } /* red */
        pre { border-radius: 8px; max-height: 400px; overflow-y: auto; }
        .endpoint-card { background-color: #1e293b; border: 1px solid #334155; border-radius: 12px; margin-bottom: 2rem; overflow: hidden; }
        .endpoint-header { background-color: #0f172a; padding: 1rem 1.5rem; border-bottom: 1px solid #334155; display: flex; align-items: center; gap: 1rem; }
        .endpoint-body { padding: 1.5rem; }
    </style>
</head>
<body class="antialiased">
    <div class="max-w-6xl mx-auto py-10 px-6">
        <header class="mb-12 border-b border-slate-700 pb-6">
            <h1 class="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-cyan-400">API Documentation</h1>
            <p class="text-slate-400 mt-2">Automatically generated by API Reverse Engineer AI</p>
        </header>

        <main>
`;

    // Map requests to a unified structure
    const unifiedMap = new Map();
    requests.forEach(req => {
        try {
            const urlObj = new URL(req.url);
            let path = urlObj.pathname;
            // Basic path parameter detection heuristic (/users/123 -> /users/:id)
            const parts = path.split('/');
            const normParts = parts.map(p => (!isNaN(p) || p.length > 20) ? ':id' : p);
            path = normParts.join('/');

            const key = `${req.method} ${path}`;
            if (!unifiedMap.has(key)) {
                unifiedMap.set(key, []);
            }
            unifiedMap.get(key).push(req);
        } catch (e) { }
    });

    unifiedMap.forEach((reqs, key) => {
        const method = key.split(' ')[0];
        const path = key.split(' ')[1] || key;
        const latest = reqs[reqs.length - 1];

        let reqBodyStr = 'No Body';
        if (latest.requestBody) {
            try { reqBodyStr = JSON.stringify(JSON.parse(latest.requestBody), null, 2); }
            catch (e) { reqBodyStr = latest.requestBody; }
        }

        let resBodyStr = latest.responseBody ? JSON.stringify(latest.responseBody, null, 2) : 'No Response Data';

        docsHtml += `
            <section class="endpoint-card">
                <div class="endpoint-header">
                    <span class="method-badge ${method}">${method}</span>
                    <h2 class="text-xl font-mono text-slate-200">${path}</h2>
                    <span class="ml-auto text-xs font-semibold text-slate-400 bg-slate-800 px-3 py-1 rounded-full">Calls captured: ${reqs.length}</span>
                </div>
                <div class="endpoint-body grid grid-cols-1 lg:grid-cols-2 gap-8">
                    
                    <div>
                        <h3 class="text-lg font-semibold text-indigo-300 mb-3">Request Payload</h3>
                        <pre><code class="language-json">${escapeHtml(reqBodyStr)}</code></pre>
                    </div>

                    <div>
                        <h3 class="text-lg font-semibold text-emerald-300 mb-3">Example Response (${latest.status})</h3>
                        <pre><code class="language-json">${escapeHtml(resBodyStr)}</code></pre>
                    </div>

                </div>
            </section>
        `;
    });

    if (unifiedMap.size === 0) {
        docsHtml += `<p class="text-slate-400">No API traffic captured yet. Keep the extension open while browsing an app.</p>`;
    }

    docsHtml += `
        </main>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/prism.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-json.min.js"></script>
</body>
</html>`;

    return docsHtml;
}

function escapeHtml(unsafe) {
    return String(unsafe)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");
}
